server:
  port: 8010
  address: 0.0.0.0
spring:
  application:
    name: microservice-consumer-order
  cloud:
    consul:
      discovery:
        healthCheckInterval: 3s
      host: ${CONSUL_URI:localhost}
      port: ${CONSUL_PORT:8500}
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true
hystrix:
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 1
    execution:
      isolation:
        thread:
          timeoutInMilliseconds: 4000