server:
  port: 8031
spring:
  application:
    name: microservice-hystrix-turbine
  cloud:
    consul:
      discovery:
        healthCheckInterval: 3s
      host: ${CONSUL_URI:localhost}
      port: ${CONSUL_PORT:8500}
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true
turbine:
  appConfig: microservice-consumer-order,microservice-consumer-order-feign-hystrix-fallback-stream
  clusterNameExpression: "'default'"
  InstanceMonitor:
    eventStream:
      skipLineLogic:
        enabled: false

  
  